@startmindmap
* Rust Programming Language
** 内存管理
*** 堆栈
*** 所有权
**** 生命周期
**** 所有权规则
** 类型
*** 类型系统
**** 特点
**** 多态
***** generic
***** trait bound
***** trait object
*** 数据结构
**** 智能指针
**** 集合容器
**** 错误处理
**** 闭包
** 控制流
*** 绑定
*** 条件
*** 循环
*** 匹配
** 模块化
*** 函数
*** crate
*** workspace
** 高级话题
*** 宏编程
*** 并发异步
*** 混合编程
*** 网络开发
**** 网络协议
**** 网络模型
@endmindmap