@startmindmap
* 函数、闭包和迭代器
** 函数
*** 函数签名
**** 传入类型
**** 返回类型
*** 函数体
**** 花括号
**** 块表达式
**** return提前返回
**** 最后一行不加分号可返回
*** CTFE
**** 类似python的属性方法
**** miri
**** const fn
**** const trait fn
**** const generics
*** 函数指针
*** 函数重载
*** 函数式编程
**** 高阶函数
***** 标准库中的高阶函数
***** 自定义高阶函数
**** 柯里化
**** 并发编程中的函数式编程
***** MapReduce
***** 函数式编程在多线程中的应用
** 闭包
*** 闭包特性
**** 函数调用
**** 捕获上下文环境的自由变量
***** 复制
***** 可变
***** 移动
**** 自动推断输入和返回的类型
**** 返回闭包需要move
***** 默认按引用捕获变量
***** 整个函数调用完毕后函数内的本地变量会被销毁
***** 使用move来转移所有权到闭包内，否则出现悬垂指针
*** 闭包实现
**** 匿名结构体
***** 不占用堆内存，拥有更高性能
***** 无法实现trait
***** 使用内联技术优化
**** trait
***** 根据环境变量类型决定
****** Fn
******* 未捕获自动实现
******* 复制捕获自动实现
****** FnMut
******* 修改捕获自动实现
****** FnOnce
******* 移动捕获自动实现
***** 使用方式
****** 作为函数参数
******* trait bound
******* trait object
****** 作为函数返回值
******* impl FnOnce
******* impl FnMut
******* impl Fn
******* impl FnBox
*** 闭包示例
**** 闭包作为返回值
***** [[https://github.com/KuanHsiaoKuo/rust_lab/blob/ce6ea9db1fda392045518b400af5db5cbc9a9f62/rust_programming_dao/src/ch02_language_essentials/function.rs#L219 静态分发]]
***** [[https://github.com/KuanHsiaoKuo/rust_lab/blob/ce6ea9db1fda392045518b400af5db5cbc9a9f62/rust_programming_dao/src/ch02_language_essentials/function.rs#L187 动态分发]]
**** 闭包作为参数传递
***** 传递原始函数指针
***** 传递闭包
** 迭代器
*** 迭代器的定义和分类
**** 惰性迭代器和及早求值迭代器
**** 可变迭代器和不可变迭代器
**** 单向迭代器和双向迭代器
**** 分类详解
***** 可复制的迭代器
***** 不可复制的迭代器
***** 含状态的迭代器
***** 不含状态的迭代器
*** 实现了迭代器 trait 的标准库类型
**** Iterator trait
**** IntoIterator trait
**** DoubleEndedIterator trait
*** 迭代器的使用
**** 迭代器适配器
***** 过滤器 filter
***** 映射器 map
***** 扁平化器 flat_map
***** 取消前缀器 skip
***** 取消后缀器 take
***** 合并器 zip
***** 非消费型迭代器 peekable
***** 反转器 rev
***** 排序器 sorted
***** 重复器 cycle
***** 镜像器 cloned
***** 分割器 split
**** 迭代器消费器
***** 类型转换器 collect
***** 折叠器 fold
***** 查找器 find
***** 判断器 all 和 any
***** 统计器 count
***** 约束器 take_while 和 skip_while
***** 最大最小值 max 和 min
***** 标准库迭代器消费器实现列表
*** 迭代器的实现
**** 自定义迭代器 trait
**** 实现迭代器 trait
***** for 循环迭代器
***** while 循环迭代器
@endmindmap