@startmindmap

* 类型系统
** 特点
*** 类型安全
**** 意义明确
**** 行为约束
*** 类型推导
*** 类型转换
**** 常用转换
***** From/Into Series
****** TryFrom/TryInto
****** FromStr/TryFromStr
***** as Series
****** AsRef/AsMut
***** Borrow/BorrowMut
***** Deref
**** Deref解引用
***** 解引用强制多态
***** 自动解引用
****** 方便开发者使用智能指针
****** 开发者可以定义行为
******* Deref/DerefMut
******** 内部实现
******** 应用场景
****** 手动解引用
******* Rc<T>
******* match
******** match x.deref()
******** match x.as_ref()
******** match x.borrow()
******** match &*x
******** match &x[..]
***** as 操作符
****** 常用场景
******* 无歧义完全限定语法
******* 父子类型相互转化
***** From/Into
***** TryFrom/TryInto
***** AsRef/AsMut
***** FromStr/TryFromStr
*** 类型别名
*** 类型标记
*** 类型大小
** 多态
*** 基础
**** generic
**** trait bound
*** 特化
**** 直接实现
**** 派生实现
**** 特别实现
*** trait object
** 核心
*** generic
**** 编译期自动实现代码
**** 中间件原则：泛型优先于trait object
**** 泛型优化
***** 模板
***** Monomorphization
***** lazy static
***** macro_rules!
**** 动态分发
***** vtable
***** 抽象基石
*** trait
**** 零成本抽象基石
***** 唯一接口抽象方式
***** 动静皆宜
***** 标签🏷️
**** 实现所有抽象\n运行时零开销
***** 接口抽象
***** OOP抽象
***** FP抽象
***** 泛型抽象
**** 行为约束
***** 接口约束
****** 最基础用法
****** 实现与重载
******* 关联类型
******* trait一致性
******* trait继承
***** 泛型约束
****** 又叫trait限定
****** 方法集合
****** 组合优于继承的体现
****** 单态化静态分发
****** where子句重构
***** 抽象类型
****** trait object
******* 动态分发
******* 组成
******** data指针
******** vtable指针
********* 析构函数
********* 大小
********* 对齐
********* 方法
******** 对象安全
********* 类型参数self
********* 使用规则
********* 三点要求
****** impl trait
******* 静态分发
******* 拆箱抽象类型
******* 使用场景
******** 作为函数参数
******** 作为函数返回值
******** 作为结构体字段
******** 作为枚举体成员
***** 标签trait
@endmindmap