@startmindmap
* 错误处理
** 分层错误处理(基于枚举体)
*** Option<T>
**** Some(T)
**** None
**** map
**** and_then
**** unwrap
**** expect
**** ...
*** Result<T, E>
**** Ok(T)
**** Err(E)
**** ?运算符
**** try!
**** match
**** ...
** 错误类型的定义
*** 组合错误类型
*** 自定义错误类型
*** 标准库提供的错误类型
*** ...
** 上下文传递
*** 链式传递
*** 返回错误类型的函数
*** ...
** 日志记录
*** log和env_logger
*** slog和slog-stdlog
*** tracing
*** ...
** 最佳实践
*** 错误类型应尽量进行精细划分
*** unwrap和expect应避免在生产环境中使用
*** Option和Result应合理使用，避免过度使用
*** 应该对捕捉到的错误进行分类处理
*** ...
@endmindmap