@startmindmap
* 从编程抽象体系看rust
** I. 底层抽象
*** 虚拟内存管理
*** 语言语法
*** 类型系统
** II. 设计抽象
*** 数据结构
*** 控制流
*** 设计模式
*** 模块编程
*** 编程范式
** III. 任务抽象
*** 并发
*** 异步
*** 元编程
** IV. 协议抽象
*** 跨语言
*** 计算机网络
@endmindmap