@startmindmap
* 区块链与web3
** 基础层（Layer1）
*** 区块链协议
**** 比特币
**** 以太坊
**** EOS
**** 等
*** 共识算法
**** 工作量证明
**** 权益证明
**** Delegated Proof of Stake
**** 等
*** 加密算法
**** 哈希算法
**** 非对称加密算法
**** 对称加密算法
**** 等
*** 区块链基础知识
**** 区块
**** 交易
**** 节点
**** 挖矿
**** 智能合约
**** 等

** 扩展层（Layer2）
*** 侧链
**** IOST
**** 跨链技术
**** 等
*** 集成层
**** IPFS
**** OrbitDB
**** Swarm
**** 等
*** 二层扩展
**** 闪电网络
**** Plasma

** 应用层（Layer3）
*** 去中心化交换协议（DEX）
*** 去中心化金融（DeFi）应用
*** 区块链游戏
*** 区块链溯源应用
*** 区块链存证应用等

** Web3开发层级
*** Web3基础知识层
**** Solidity语言
**** 智能合约编写
**** 以太坊、EOS等区块链的RPC交互方式等
*** 架构层
**** 前端层：HTML、CSS、JavaScript、MVC等
**** 后端层：web框架、数据库、RPC、RESTful API等
**** 区块链层：节点管理、通信协议、事件调度等
*** 安全层
**** 非对称加密算法：RSA、ECDSA等
**** 智能合约安全编写：防止重入攻击、避免整数溢出等
**** 数据加密和数字签名
**** 零知识证明：用于确保数据的隐私性的加密技术，通常被应用于区块链中的隐私保护方案，例如匿名交易等。
*** 网络层
**** 点对点网络
**** 矿工
**** 节点
@endmindmap