@startmindmap
* 控制流
** 绑定
*** let变量
**** 可以多次绑定同名变量
**** 可以使用模式匹配
**** 只能绑定不可变变量
*** const常量
**** 必须在声明时初始化
**** 只能绑定不可变变量
** 运算符与表达式
*** 算术运算符：+ - * / %
*** 比较运算符：== != > >= < <=
*** 逻辑运算符：&& || !
*** 位运算符：& | ^ ~ << >>
*** 赋值运算符：= += -= *= /= %=
*** 运算符的优先级：表达式中先进行哪些运算
** 条件
*** if语句：if...else if...else if...else...
**** 可以在if语句中使用let绑定
**** 可以在if语句中使用表达式作为条件
*** match表达式：类似于switch语句
**** 所有分支必须返回同一个类型
**** 所有分支必须穷尽所有可能
**** 所有分支必须是不可变的
**** 一般会用"_"来匹配剩余的情况
**** 匹配模式
***** 单值：匹配单个值
***** 范围：1..3
***** 多值: |5|7|13
***** 通配符: _
***** 绑定: x @ 1..3\nx可以在右侧使用
*** if let表达式：在match表达式中if可以过滤掉不需要的分支
*** while let表达式：在循环中使用match匹配和绑定
** 循环
*** while循环：while...{}
**** 可以在循环中使用let绑定
*** for循环：for...in...{}
**** 可以迭代数组、范围、迭代器等
**** 可以使用if判断条件
@endmindmap