@startmindmap
* 数据结构（数据类型）
** 基本数据类型
*** 布尔
*** 数字
**** 类型前后缀
**** 字面量
***** 整数字面量
****** 十进制
****** 二进制
****** 八进制
****** 十六进制
***** 浮点数字面量
****** 十进制
****** 科学计数法
****** 十六进制
****** 八进制
****** 二进制
***** 字节字面量
**** 整数
***** 固定大小
****** 符号整数
******* i8
******* i16
******* i32
******* i64
******* i128
****** 无符号
******* u8
******* u16
******* u32
******* u64
******* u128
***** 动态大小
****** isize
****** usize
**** 浮点
***** f32
***** f64
*** 字符
**** character
***** Unicode标准
***** ASCII
***** Unicode标量值
***** 字符集
**** String
***** 特点
****** 本质是切片
****** 通常是不可变借用
***** 分类
****** str: 固定长度
****** String：可增长长度
***** 组成
****** 指针
****** 长度
***** 方法
****** as
******* as_bytes
******* as_bytes_mut
******* as_ptr
******* as_mut_ptr
******* as_str
******* as_mut_str
******* as_os_str
******* as_os_str_lossy
******* as_c_str
******* as_mut_c_str
****** len
****** is
******* is_empty
******* is_char_boundary
****** chars
****** char_indices
****** bytes
****** split
******* split_terminator
******* splitn
******* rsplit
******* rsplitn
******* split_whitespace
******* split_at
******* split_at_mut
******* split_off
******* split_to
******* split_to_mut
****** lines
****** lines_any
****** match
******* match_indices
******* rmatch_indices
******* match_indices_any
******* rmatch_indices_any
****** contain
******* contains
******* contains_char
******* starts_with
******* ends_with
****** find
******* find
******* rfind
******* find_str
****** slice
******* slice
******* slice_mut
******* slice_unchecked
******* slice_unchecked_mut
****** get
******* get
******* get_mut
******* get_unchecked
******* get_unchecked_mut
*** 指针
**** 指针、引用、借用
**** 分类
***** 引用（非空指针）
***** 裸指针(原生指针)
***** 函数指针
***** 智能指针
****** Reference(&T or &mut T)
****** Box<T>
****** LocalBox<T>
****** Rc<T>
****** Arc<T>
****** Cell<T>
****** RefCell<T>
****** Mutex<T>
****** RwLock<T>
****** Atomic<T>
****** Pin<T>
****** ManuallyDrop<T>
****** NonNull<T>
****** PhantomData<T>
****** UnsafeCell<T>
****** Unique<T>
****** Weak<T>
*** never
** 集合容器
*** 线性序列
**** 数组
**** 切片
***** 本质上是一个指针
***** 是对数组的引用
**** 向量
**** 链表
***** 单向链表
***** 双向链表
**** 队列
***** VecDeque
***** PriorityQueue
***** ArrayQueue
***** LinkedList
***** CircularBuffer
*** 映射表
**** 哈希表
***** HashMap
**** 树
***** B-tree
***** 红黑树
***** AVL树
***** Treap
***** Splay树
***** 伸展树
**** 前缀树
**** Trie树
*** 集合
**** HashSet
**** BTreeSet
*** 堆
**** BinaryHeap
**** FibonacciHeap
**** PairingHeap
** 复合数据类型
*** 元组
**** Tuple
**** NamedTuple
*** 结构体
**** Struct
**** Enum
**** Union
**** Attribute
**** Marker
**** TupleStruct
**** Unit
**** UnitStruct
**** Field
**** Visibility
*** 枚举
**** Enum
***** Option<T>
****** Some(T)
****** None
****** map
****** and_then
****** unwrap
****** expect
****** ...
***** Result<T, E>
****** Ok(T)
****** Err(E)
****** ?运算符
***** Panic
***** Abort
*** 联合体
** 分层错误处理(基于枚举体, 详见错误处理主题)
*** Option<T>
**** Some(T)
**** None
**** map
**** and_then
**** unwrap
**** expect
**** ...
*** Result<T, E>
**** Ok(T)
**** Err(E)
**** ?运算符
*** Panic
**** catch_wind
**** set_hook
*** Abort
@endmindmap