@startmindmap
* 基于LLM的训练平台(Rust)
**:结构
<code>
md_file:embedding_vector_knowledge_seq.md
</code>;
***:Embedding
<code>
md_file:what_is_embedding.md
</code>;
****:处理过程
<code>
md_file:embedding_flow.md
</code>;
***:Vector Database
<code>
md_file:what_is_vector_database.md
</code>;
****:包含内容
<code>
md_file:vector_database_contains.md
</code>;
**** [[https://github.com/qdrant/qdrant qdrant/qdrant]]
*****:README
<code>
md_file:qdrant_readme.md
</code>;
** 多角度
***:三个指标
<code>
md_file:system_performance_metrics.md
</code>;
**** 高性能
**** 高并发
**** 高吞吐
**** 体现项目
*****:[[https://github.com/orgs/tokio-rs/repositories?type=source Tokio生态]]
<code>
md_file:tokio_env.md
</code>;
******:[[https://github.com/tokio-rs/tokio Tokio Runtime]]
<code>
A runtime for writing reliable asynchronous applications with Rust. Provides I/O, networking, scheduling, timers, ...
</code>;
*******:README
<code>
md_file:tokio_readme.md
</code>;
******:[[https://github.com/tokio-rs/console tokio-console]]
<code>
a debugger for async rust!
</code>;
*******:README
<code>
md_file:tokio-console-readme.md
</code>;
******:[[https://github.com/tokio-rs/axum tokio-rs/axum]]
<code>
Ergonomic and modular web framework built with Tokio, Tower, and Hyper
</code>;
*******:README
<code>
md_file:tokio-axum-readme.md
</code>;
******:[[https://github.com/tokio-rs/tracing tokio-rs/tracing]]
<code>
Application level tracing for Rust.
</code>;
*******:README
<code>
md_file:tokio-tracing-readme.md
</code>;
*******:[[https://github.com/tokio-rs/tracing-opentelemetry tokio-rs/tracing-opentelemetry]]
<code>
Utilities for adding OpenTelemetry interoperability to tracing.
</code>;
********:README
<code>
md_file:tokio-tracing-opentelemetry-readme.md
</code>;
******:[[https://github.com/tokio-rs/loom tokio-rs/loom]]
<code>
Concurrency permutation testing tool for Rust.
</code>;
*******:README
<code>
md_file:tokio-loom-readme.md
</code>;
******:[[https://github.com/tokio-rs/tokio-uring tokio-rs/tokio-uring]]
<code>
An io_uring backed runtime for Rust
</code>;
*******:README
<code>
md_file:tokio-uring-readme.md
</code>;
******:[[https://github.com/tokio-rs/prost tokio-rs/prost]]
<code>
PROST! a Protocol Buffers implementation for the Rust Language
</code>;
*******:README
<code>
md_file:tokio-prost-readme.md
</code>;
******: [[https://github.com/tokio-rs/io-uring tokio-rs/io-uring]]
<code>
The `io_uring` library for Rust
</code>;
*******: README
<code>
md_file:tokio-io-uring-readme.md
</code>;
******:[[https://github.com/tokio-rs/turmoil tokio-rs/turmoil]]
<code>
## This is very experimental

Add hardship to your tests.

Turmoil is a framework for testing distributed systems.
It provides deterministic execution by running multiple concurrent hosts within a single thread.
It introduces "hardship" into the system via changes in the simulated network.
The network can be controlled manually or with a seeded rng.
</code>;
******:[[https://github.com/tokio-rs/mio tokio-rs/mio]]
<code>
Metal I/O library for Rust.
> Mio is a fast, low-level I/O library for Rust focusing on non-blocking APIs and
> event notification for building high performance I/O apps with as little overhead
> as possible over the OS abstractions.
</code>;
******:[[https://github.com/tokio-rs/tokio-metrics tokio-rs/tokio-metrics]]
<code>
Utilities for collecting metrics from a Tokio application
Provides utilities for collecting metrics from a Tokio application, including runtime and per-task metrics.
</code>;
*** 处理引擎（来源于大数据）
**** 批处理
**** 流处理
***** Flink(JAVA)
*****:[[https://github.com/ArroyoSystems/arroyo ArroyoSystems/arroyo]]
<code>
Distributed stream processing engine in Rust
</code>;
******: 介绍
<code>
md_file:arroyo_intro.md
</code>;
*** 参考项目
****:[[https://github.com/BaguaSys/bagua bagua: 已鸽]]
<code>
md_file:bagua_readme.md
</code>;
****:[[https://github.com/hpcaitech/ColossalAI CollssalAI-python]]
<code>
md_file:collssal_ai_readme.md
</code>;
****:[[https://github.com/vaaaaanquish/Awesome-Rust-MachineLearning vaaaaanquish/Awesome-Rust-MachineLearning]]
<code>
This repository is a list of machine learning libraries written in Rust. It's a compilation of GitHub repositories, blogs, books, movies, discussions, papers, etc.
</code>;
**** [[https://github.com/BinChengZhao/delicate BinChengZhao/delicate]]
*****:README
<code>
md_file:delicate_readme.md
</code>;
@endmindmap
