@startmindmap
* 内存管理
** safe
*** 内存布局
**** 内存对齐
**** 字节对齐
*** 堆栈
**** 栈
***** 默认放在栈上
**** 堆
***** 堆数据结构
***** 堆内存
***** 堆分配
****** 链表
****** 位图
*** 分配与释放
**** 内存分配器
***** 系统分配器
***** 自定义分配器
****** jemalloc
****** tcmalloc
*** 所有权
**** 单一所有权
***** Copy/Move
***** 借用
****** 借用规则
******* 三条规则
******* 规则缺陷
******* MIR
******* NLL(非词法作用域)
****** 借用检查
****** 解引用获得所有权
***** 生命周期
****** 生命周期参数
******* 函数签名
******* 方法签名
******* 结构体/枚举体
******* 静态
****** 生命周期省略
****** trait对象生命周期
****** 泛型生命周期
***** 所有权规则
**** 共享所有权(Rc<T>和Weak<T>)
** unsafe
*** 裸指针
*** 型变
*** Drop检查
*** FFI
*** WebAssembly
@endmindmap
