@startmindmap
* 控制流
** 绑定
*** let变量
*** const常量
** 运算符与表达式
** 条件与循环
** 模式匹配
*** match表达式
**** 所有分支必须返回同一个类型
**** 所有分支必须穷尽所有可能
**** 所有分支必须是不可变的
**** 一般会用"_"来匹配剩余的情况
**** 匹配模式
***** 单值：匹配单个值
***** 范围：1..3
***** 多值: |5|7|13
***** 通配符: _
***** 绑定: x @ 1..3\nx可以在右侧使用
*** if let表达式
*** while let表达式
@endmindmap